In [ ]:
#MISSING DATA

In [1]:
import numpy as np
import pandas as pd

In [11]:
#FINDING MISSING DATA

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

In [12]:
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [14]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [15]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [17]:
#REMOVING MISSING DATA
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0